### ISSUE TITLE
Cannot compile with libcheck-0.9.9

### ISSUE THREAD

**Issue by pakmarkthub** [NVIDIA/gdrcopy#174]
```
make[1]: Entering directory `/home/pmarkthub/Projects/gdrcopy/tests'
g++ -O2 -I /usr/local/cuda/include -I ../include -I ../src -I /usr/local/cuda/include   -L /usr/local/cuda/lib64 -L /usr/local/cuda/lib -L /usr/lib64/nvidia -L /usr/lib/nvidia -L /usr/local/cuda/lib64 -L ../src   -o sanity sanity.o common.o -lcuda -lpthread -ldl -lgdrapi -lcheck  
sanity.o: In function `invalidation_unix_sock_shared_fd_gdr_pin_buffer_fn(int)':
sanity.cpp:(.text+0xa90): undefined reference to `_ck_assert_failed'
sanity.cpp:(.text+0xac7): undefined reference to `_ck_assert_failed'
sanity.o: In function `invalidation_access_after_gdr_close_fn(int)':
sanity.cpp:(.text+0xfdf): undefined reference to `_ck_assert_failed'
sanity.cpp:(.text+0x1016): undefined reference to `_ck_assert_failed'
sanity.o: In function `basic_child_thread_pins_buffer_fn(int)':
sanity.cpp:(.text+0x15c0): undefined reference to `_ck_assert_failed'
sanity.o:sanity.cpp:(.text+0x15f7): more undefined references to `_ck_assert_failed' follow
collect2: error: ld returned 1 exit status
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/home/pmarkthub/Projects/gdrcopy/tests'
make: *** [exes] Error 2
```

libcheck version:
```
$ rpm -q check
check-0.9.9-5.el7.x86_64

$ rpm -q check-devel
check-devel-0.9.9-5.el7.x86_64
```

**Comment by pakmarkthub** [comment]
This is a human error. I mistakenly compiled with libcheck header from the master branch, which is not released yet, and tried to link against libcheck.so from `check-0.9.9-5.el7.x86_64`.
