### ISSUE TITLE
gdrdrv does on build on 5.10+

### ISSUE THREAD

**Issue by drossetti** [NVIDIA/gdrcopy#161]
kzfee has been removed from the Linux kernel since 5.10-rc1
```
CC [M]  /home/lab/IMB/gdrcopy-2.1/src/gdrdrv/gdrdrv.o
/home/lab/IMB/gdrcopy-2.1/src/gdrdrv/gdrdrv.c: In function ‘gdrdrv_release’:
/home/lab/IMB/gdrcopy-2.1/src/gdrdrv/gdrdrv.c:384:9: error: implicit declaration of function ‘kzfree’; did you mean ‘kvfree’?
```

**Comment by drossetti** [comment]
@pakmarkthub I think we can simply replace kzfree() with memset()+kfree(), right?

**Comment by drossetti** [comment]
actually kzfree() has been renamed, see https://github.com/torvalds/linux/commit/453431a54934d917153c65211b2dabf45562ca88

**Comment by drossetti** [comment]
probably simply using kfree() is enough... there is nothing really sensible in those mr objects

**Comment by pakmarkthub** [comment]
The PR has been merged. Closing this issue.
