### ISSUE TITLE
Ubuntu 26.04 incompatibility when building gdrcopy Debian packages

### ISSUE THREAD

**Issue by sid1994** [NVIDIA/gdrcopy#339]
On Ubuntu 26.04, building the gdrcopy libgdrapi 2.5.2 Debian packages fails during dpkg-buildpackage with a dpkg-source error related to the 3.0 (quilt) source format and non-native versioning.

Environment
OS: Ubuntu 26.04, x86_64 (see notes)
gdrcopy version: 2.5.2 (libgdrapi-2.5.2 source tree)
The same gdrcopy source and packaging flow do not exhibit this issue on earlier Ubuntu versions; we only see the failure on Ubuntu 26.04.

Steps to Reproduce
1. On Ubuntu 26.04 x86_64, obtain the gdrcopy version 2.5.2.
2. Build gdrcopy, and run the packages/build-deb-packages.sh script.

Failure output
...
dpkg-source -b .
dpkg-source: error: cannot build with source format '3.0 (quilt)': non-native package version does not contain a revision
dpkg-buildpackage: error: dpkg-source -b . subprocess failed with exit status 25
debuild: fatal error at line 1185:
dpkg-buildpackage -d -us -uc -ui failed
...

Notes / Current Status
This problem was detected on gdrcopy 2.5.2 which does not support Ubuntu 26.04, and therefore runs into this packaging failure.
Other gdrcopy versions (depending on the version) may also suffer from this problem.
The error is caused by stricter Debian tooling behavior in Ubuntu 26.04 around non-native package versions used with the 3.0 (quilt) source format (e.g., requiring a Debian revision in the version string).
While older dpkg versions in previous Ubuntu distributions were relaxed, new dpkg version shipped with Ubuntu 26 strictly enforces the requirement of Debian revision in the version string.
We plan to address this problem in gdrcopy 2.6 which will likely be released sometime in May.

**Comment by Zhenye-Na** [comment]
I am observing similar issues when installing GDRCopy 2.5.2 on Ubuntu 26.04, so just adding here for visibility

**gdrcopy 2.5.2 `pplat.cu` fails to compile on Ubuntu 26.04 (GCC 15 + CUDA 13.3 + Nvidia Proprietary Driver)**

Hitting this on Ubuntu 26.04 with GCC 15.2 and CUDA 13.3. The `pplat.cu` test binary fails with 34 errors even with `--allow-unsupported-compiler`.

**Environment:**
- Ubuntu 26.04, kernel 7.0.0-1004-aws
- GCC 15.2.0
- CUDA 13.3 (nvcc)
- gdrcopy 2.5.2


```
/usr/include/c++/15/type_traits(555): error: type name is not allowed
      : public __bool_constant<__is_pointer(_Tp)>

/usr/include/c++/15/type_traits(877): error: identifier "__is_volatile" is undefined

/usr/include/c++/15/bits/new_allocator.h(147): error: identifier "__builtin_operator_new" is undefined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(83): error: exception specification is incompatible with that of previous function "cospi"
```

**Comment by sid1994** [comment]
Hello, your error seems to be unrelated to the above gdrcopy issue about building deb packages.
Moreover, your error also seems unrelated to Ubuntu 26.04 or pplat, and it might be stemming from an old or mixed CUDA install, which is causing problems with gcc 15.2.

I tried to reproduce it with the following environment
Environment
- Ubuntu 26.04, 7.0.0-22-generic
- nvcc --version = 13.3, V13.3.29
- gcc -v = 15.2.0 (Ubuntu 15.2.0-16ubuntu1)
- gdrcopy 2.5.2

Running make CUDA=/usr/local/cuda-13.3 all -j
should lead to
/usr/local/cuda-13.3/bin/nvcc -o pplat.o -c pplat.cu -lcuda -lpthread -ldl -lgdrapi -I /usr/local/cuda-13.3/include -I ../include -I ../src -I /usr/local/cuda-13.3/include -arch=all --std=c++17
which succeeds without any errors for me.

Please try reinstalling CUDA 13.3 from scratch, maybe on a fresh Ubuntu 26 machine if possible.

**Comment by Zhenye-Na** [comment]
Thanks for the pointer! I checked our build process — we call `CUDA=/usr/local/cuda ./build-deb-packages.sh` and I found that `/usr/local/cuda` was resolving to CUDA 12.8 (not 13.2/13.3) on our proprietary driver builds.

~~I'm planning to switch our proprietary path to also install CUDA 13.2 so the symlink resolves correctly - does that sound like the right approach to you?~~

We could build GDRCopy 2.5.2 on Ubuntu 26 with Proprietary Drive, CUDA 13.2 now

**Comment by sid1994** [comment]
GDRCopy 2.6 is released: https://github.com/NVIDIA/gdrcopy/releases/tag/v2.6
Debian packages can now be built successfully.
Closing this issue.
